# Generated by Django 3.2.6 on 2024-11-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='valor',
            field=models.CharField(max_length=512),
        ),
    ]
