# Generated by Django 3.2.6 on 2024-10-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0002_alter_recibo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibo',
            name='id',
        ),
        migrations.AlterField(
            model_name='recibo',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
