# Generated by Django 3.2.6 on 2024-10-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0002_alter_institucion_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='institucion',
            table=None,
        ),
    ]
