# Generated by Django 3.2.6 on 2024-10-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0003_alter_institucion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
